# Orbital Debris SQL Queries

This notebook is intentionally SQL-first and contains query work only (no visualizations).

## **Setup And Function Declarations**

In [1]:
import pandas as pd
import sqlite3 as sql
import utility as utils

orbital_debris_conn = sql.connect('../data/clean/orbital_debris.db')

# Sanity Check - Verify that the database connection is working and that we can retrieve data
sanity_check_no_decayed = utils.query_all_satellites(orbital_debris_conn, include_decayed=False)
display(sanity_check_no_decayed)

sanity_check_all = utils.query_all_satellites(orbital_debris_conn)
display(sanity_check_all)

,norad_id,cospar_id,object_name,satellite_name,official_name,object_type,category,ops_status,data_status,decay_date,...,users,is_commercial,is_government,is_military,is_civil,contractor,contractor_country,launch_date,launch_year,launch_site
4,5,1958-002B,VANGUARD 1,None,None,PAYLOAD,Inactive Satellite,UNKNOWN,None,None,...,Civil,1,1,1,1,Amsat-NA,USA,1958-03-17,1958,AFETR
10,11,1959-001A,VANGUARD 2,None,None,PAYLOAD,Inactive Satellite,UNKNOWN,None,None,...,Civil,1,1,1,1,Amsat-NA,USA,1959-02-17,1959,AFETR
11,12,1959-001B,VANGUARD R/B,None,None,ROCKET BODY,Rocket Body,UNKNOWN,None,None,...,Civil,1,1,1,1,Amsat-NA,USA,1959-02-17,1959,AFETR
15,16,1958-002A,VANGUARD R/B,None,None,ROCKET BODY,Rocket Body,UNKNOWN,None,None,...,Civil,1,1,1,1,Amsat-NA,USA,1958-03-17,1958,AFETR
19,20,1959-007A,VANGUARD 3,None,None,PAYLOAD,Inactive Satellite,UNKNOWN,None,None,...,Civil,1,1,1,1,Amsat-NA,USA,1959-09-18,1959,AFETR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68356,68539,2026-069B,TACHELES,None,None,PAYLOAD,Active Satellite,OPERATIONAL,None,None,...,Government,1,1,1,1,"Institute of Aeronautics and Astronautics, Tec...",Germany,2026-04-01,2026,AFETR
68357,68540,2026-069C,SWC-1,None,None,PAYLOAD,Active Satellite,OPERATIONAL,None,None,...,Government,1,1,0,1,"Space Research Institute, King Abdulaziz City ...",Saudi Arabia,2026-04-01,2026,AFETR
68358,68541,2026-069D,K-RADCUBE,None,None,PAYLOAD,Active Satellite,OPERATIONAL,None,None,...,Government/Commercial,1,1,1,1,Korea Aerospace Research Institute (KARI)/ EAD...,South Korea/France/UK/Germany,2026-04-01,2026,AFETR
68359,68571,2026-071A,OBJECT A,None,None,PAYLOAD,Active Satellite,OPERATIONAL,None,None,...,Military,1,1,1,1,NPO/PM - Scientific Research Institute for Pre...,Russia,2026-04-03,2026,PLMSC
68360,68572,2026-071B,OBJECT B,None,None,ROCKET BODY,Rocket Body,UNKNOWN,None,None,...,Military,1,1,1,1,NPO/PM - Scientific Research Institute for Pre...,Russia,2026-04-03,2026,PLMSC

,norad_id,cospar_id,object_name,satellite_name,official_name,object_type,category,ops_status,data_status,decay_date,...,users,is_commercial,is_government,is_military,is_civil,contractor,contractor_country,launch_date,launch_year,launch_site
0,1,1957-001A,SL-1 R/B,None,None,ROCKET BODY,Rocket Body,DECAYED,None,1957-12-01,...,Military,1,1,1,1,NPO/PM - Scientific Research Institute for Pre...,Russia,1957-10-04,1957,TYMSC
1,2,1957-001B,SPUTNIK 1,None,None,PAYLOAD,Inactive Satellite,DECAYED,None,1958-01-03,...,Military,1,1,1,1,NPO/PM - Scientific Research Institute for Pre...,Russia,1957-10-04,1957,TYMSC
2,3,1957-002A,SPUTNIK 2,None,None,PAYLOAD,Inactive Satellite,DECAYED,None,1958-04-14,...,Military,1,1,1,1,NPO/PM - Scientific Research Institute for Pre...,Russia,1957-11-03,1957,TYMSC
3,4,1958-001A,EXPLORER 1,None,None,PAYLOAD,Inactive Satellite,DECAYED,None,1970-03-31,...,Civil,1,1,1,1,Amsat-NA,USA,1958-02-01,1958,AFETR
4,5,1958-002B,VANGUARD 1,None,None,PAYLOAD,Inactive Satellite,UNKNOWN,None,None,...,Civil,1,1,1,1,Amsat-NA,USA,1958-03-17,1958,AFETR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68356,68539,2026-069B,TACHELES,None,None,PAYLOAD,Active Satellite,OPERATIONAL,None,None,...,Government,1,1,1,1,"Institute of Aeronautics and Astronautics, Tec...",Germany,2026-04-01,2026,AFETR
68357,68540,2026-069C,SWC-1,None,None,PAYLOAD,Active Satellite,OPERATIONAL,None,None,...,Government,1,1,0,1,"Space Research Institute, King Abdulaziz City ...",Saudi Arabia,2026-04-01,2026,AFETR
68358,68541,2026-069D,K-RADCUBE,None,None,PAYLOAD,Active Satellite,OPERATIONAL,None,None,...,Government/Commercial,1,1,1,1,Korea Aerospace Research Institute (KARI)/ EAD...,South Korea/France/UK/Germany,2026-04-01,2026,AFETR
68359,68571,2026-071A,OBJECT A,None,None,PAYLOAD,Active Satellite,OPERATIONAL,None,None,...,Military,1,1,1,1,NPO/PM - Scientific Research Institute for Pre...,Russia,2026-04-03,2026,PLMSC
68360,68572,2026-071B,OBJECT B,None,None,ROCKET BODY,Rocket Body,UNKNOWN,None,None,...,Military,1,1,1,1,NPO/PM - Scientific Research Institute for Pre...,Russia,2026-04-03,2026,PLMSC

## Primary Question 1: Growth and Decoupling Baseline
At what year does the present day in-orbit population stop following a legacy linear pattern and transition into a modern accelerating pattern?

## **Primary Question 2: High-Risk Distribution by Altitude Band**
How are high-risk objects (by velocity and kinetic energy) distributed across orbit classes and altitude bands, especially in the 400 - 600 km LEO?

## **Primary Question 3: Zombie Concentration by Owner**

## **Secondary: Object Type × Operational Status**

## **Secondary: User Category Profile**

## **Extra Questions!**